blank_issues_enabled: false

# Issueä½œæˆæ™‚ã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆè¨­å®š
defaults:
  - template: "bug_report.yml"
    name: "ğŸ› ãƒã‚°å ±å‘Š"
    about: "ãƒã‚°ã‚’å ±å‘Šã™ã‚‹"
  - template: "feature_request.yml"
    name: "ğŸ’¡ æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆ"
    about: "æ–°æ©Ÿèƒ½ã®ã‚¢ã‚¤ãƒ‡ã‚¢ã‚’ææ¡ˆã™ã‚‹"
  - template: "mentenance_request.yml"
    name: "ğŸ’» é–‹ç™ºç’°å¢ƒã®ãƒ¡ãƒ³ãƒ†ãƒŠãƒ³ã‚¹ãƒªã‚¯ã‚¨ã‚¹ãƒˆ"
    about: "ã‚½ãƒ¼ã‚¹ã‚³ãƒ¼ãƒ‰ã‚„é–‹ç™ºã«ã‹ã‹ã‚‹ç’°å¢ƒã®ãƒ¡ãƒ³ãƒ†ãƒŠãƒ³ã‚¹ã®ã‚¢ã‚¤ãƒ‡ã‚¢ã‚’ææ¡ˆã™ã‚‹"
